name: LONEWORK PRODUCTIONS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56298
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffcd94'
    - '#7c4f49'
    - '#d68871'
    - '#f5570d'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
